### PR TITLE
add ip/mac address to network display in system page

### PR DESCRIPTION
**Pull request by sumnerboy12**
reorganise layout, titles and action texts

@austinscreations can you have a look/test and see what you think about these changes?

### CODE REVIEW

**Comment by sumnerboy12** [comment]
Here is the new firmware page...
image

**Comment by sumnerboy12** [comment]
And the new system page...
image

**Comment by sumnerboy12** [comment]
NOTE: I removed the network mode from the firmware page as this was duplicated in the system page, and felt it was better in just the one place.

**Comment by austinscreations** [comment]
awe shucks you removed network from firmware page - again main reason i thought it should be there was a because it made it quick and simple to know if i'm uploading eth or wifi versions of firmware to a device.

but oh well i guess

other than that is looks good and loaded up fine on my end.

**Pull request merged**
